[package]
name = "jobs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "signal"] }

serde_json = "1.0.47"
serde = {version = "1.0.188"}
async-trait = "0.1"
mongodb = "2.6.0"
#futures = { version = "0.3", default-features = false }

[[bin]]
name = "jm"
path = "examples/simple.rs"


